version: 2.1
jobs:
  build-and-push:
    docker:
      - image: cimg/php:8.0.0
        auth: 
          username: leynebe
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      # If I needed to compile/build php or install composer packages this is where we should do it.
      - run: php --version
      # Allow us to use docker-in-docker
      - setup_remote_docker:
          version: 19.03.13
      # Do the docker build with the dockerfile in the current dir
      - run: |
          TAG=0.0.$CIRCLE_BUILD_NUM
          docker build -t leynebe/circleci-docker-rainbow:$TAG .
          docker push leynebe/circleci-docker-rainbow:$TAG
workflows:
  main:
    jobs:
      - build-and-push

