version: 2.1

orbs:
  # Link an orb that allows for docker functions
  docker: circleci/docker@1.4.0

workflows:
  main:
    jobs:
    - build-and-push:
        # Link the context that contains docker hub credentials
        context:
        - docker_hub_leynebe_context
        
jobs:
  build-and-push:
    docker:
      - image: circleci/php:8.0.0-cli-buster
        # Auth is not really needed here because we're pulling a public image
        # auth: 
        #   username: $DOCKERHUB_USERNAME
        #   password: $DOCKERHUB_PASSWORD
    steps:
      # Check out repository files
      - checkout
      # If I needed to compile/build php or install composer packages this is where we should do it.
      - run: php --version
      # Allow us to use docker-in-docker to build and push the image using docker while already in a docker container.
      - setup_remote_docker:
          version: 19.03.13
      # Makes sure we can build and we're logged in with docker
      - docker/check:
          docker-username: DOCKERHUB_USERNAME  
          docker-password: DOCKERHUB_PASSWORD 
      - docker/build:
          lint-dockerfile: true
          image: leynebe/circleci-docker-rainbow
          tag: 0.0.$CIRCLE_BUILD_NUM,latest
      - docker/push:
          image: leynebe/circleci-docker-rainbow:0.0.$CIRCLE_BUILD_NUM
      - docker/push:
          image: leynebe/circleci-docker-rainbow:latest
          
      # This is what would be used without the orb:
      # Do the docker build with the dockerfile in the current dir, login to registry and push to registry with build tag and latest tag.
      #- run: |
      #    TAG=0.0.$CIRCLE_BUILD_NUM
      #    docker build -t leynebe/circleci-docker-rainbow:$TAG .
      #    echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      #    docker tag leynebe/circleci-docker-rainbow:$TAG leynebe/circleci-docker-rainbow:latest
      #    docker push leynebe/circleci-docker-rainbow:$TAG
      #    docker push leynebe/circleci-docker-rainbow:latest


