version: 2.1
jobs:
  build-and-push:
    context:
      - docker_hub_leynebe_context
    docker:
      - image: circleci/php:8.0.0-cli-buster
        auth: 
          username: leynebe
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      # If I needed to compile/build php or install composer packages this is where we should do it.
      - run: php --version
      # Test env vars
      # From project env 
      - run: echo $BORKMEISTER
      # From context env
      - run: echo $BORKMEISTER2
      # Allow us to use docker-in-docker
      - setup_remote_docker:
          version: 19.03.13
      # Do the docker build with the dockerfile in the current dir
      - run: |
          TAG=0.0.$CIRCLE_BUILD_NUM
          docker build -t leynebe/circleci-docker-rainbow:$TAG .
          echo $DOCKERHUB_PASSWORD | docker login -u $DOCKER_USER --password-stdin
          docker push leynebe/circleci-docker-rainbow:$TAG
workflows:
  main:
    jobs:
      - build-and-push

